apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: image-processed-trigger
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.email.imageprocessed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: image-processor
