apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: converter
spec:
  template:
    metadata:
      name: converter-revision-v2
    spec:
      containers:
        - image: uhcyr/sepiaconverter
          ports:
            - containerPort: 8000
  traffic:
    - latestRevision: true
      percent: 30
    - latestRevision: false
      percent: 70
      revisionName: converter-revision-v1
